#NOTES:
# consider upper limit to k_max, as decided by theory

import numpy as np
from desc.profiles import _Profile
from desc.backend import jnp, jax


#--------------------------------- CLASS FOR OPTIMIZER ---------------------------------
class LogisticProfile(_Profile):
    """
    Profile is a superpostion of logistic/sigmoid functions,
    normalized to the input on-axis (rho=0) maximum value.
    Individual logistic functions are generated by combinations
    of given values for the steepness parameter k and shifts of
    the midpoint parameter rho_shift from rho = 0.5.

    -------- Parameters -----------------------
    p_axis: scalar
        Maximum pressure on the axis, un-normalized.
    k_range: array-like
        1-D array of parameter k in the logistic function,
        corresponding to 'steepness'.
    rho_range: array-like
        1-D array of parameter rho-shift, horizontal offset
        of the logistic function from its center at rho = 0.5.
    rho_grid: array-like
        1-D array of grid points along rho, ranging from 0 to 1.
    weights: array-like
        ("params" for optimizer)
        1-D array with optimizable weights that scales each
        unique logistic function in the superposition.
    name: str
        Optional name of the profile.
    --------- Returns ---------------

    """
    _io_attrs_ = _Profile._io_attrs_ + [
        "_params",
        "_p_axis",
        "_k_range",
        "_rho_range",
        "_rho_grid",
    ]

    # Treat structural metadata as static for JAX (prevents tracing/recompile churn)
    _static_attrs = _Profile._static_attrs + ["_k_range", "_rho_range", "_rho_grid"]

    #------------
    def __init__(
        self,
        p_axis,
        k_range,
        rho_range,
        weights,
        rho_grid,
        name="",
    ):
        super().__init__(name)  # calling parent

        #-----------------------------
        # Dtype (pick one and be consistent)
        # NOTE: float64 is typically more robust for equilibrium solves on CPU.
        dtype = jnp.float64
        #-----------------------------

        #-----------------------------
        # Defaults if inputs are None:
        p_axis_default = jnp.asarray(1e4, dtype=dtype)
        k_range_default = jnp.linspace(10, 20, 5, dtype=dtype)
        rho_range_default = jnp.linspace(-0.2, 0.2, 4, dtype=dtype)
        rho_grid_default = jnp.linspace(0.0, 1.0, 101, dtype=dtype)

        # Maxima:
        k_max = 40.0
        rho_shift_absmax = 0.2

        # Assign defaults first:
        if p_axis is None:
            p_axis = p_axis_default
        if k_range is None:
            k_range = k_range_default
        if rho_range is None:
            rho_range = rho_range_default
        if rho_grid is None:
            rho_grid = rho_grid_default

        #----------------------------
        # Ensuring JAX compatibility + dtype consistency:
        p_axis = jnp.asarray(p_axis, dtype=dtype)  # <-- JAX scalar, not python float
        k_range = jnp.atleast_1d(jnp.asarray(k_range, dtype=dtype))
        rho_range = jnp.atleast_1d(jnp.asarray(rho_range, dtype=dtype))
        rho_grid = jnp.atleast_1d(jnp.asarray(rho_grid, dtype=dtype))
        #----------------------------

        # Default weights (needs resolved k_range/rho_range):
        N_weights = int(np.asarray(k_range).size * np.asarray(rho_range).size)
        if weights is None:
            seed = jax.random.PRNGKey(0)
            weights = jax.random.uniform(
                seed,
                shape=(N_weights,),
                minval=0.0,
                maxval=1.0 / N_weights,
                dtype=dtype,
            )
        weights = jnp.atleast_1d(jnp.asarray(weights, dtype=dtype))
        #----------------------------

        #------------------
        # Error conditions (host-side checks are fine here in __init__):
        if float(p_axis) < 0:
            raise ValueError("Pressure must be positive.")

        k_host = np.asarray(k_range)
        if np.any(k_host < 0):
            raise ValueError("k must be positive")
        if np.any(k_host > k_max):
            raise ValueError(
                "Maximum k is 40. Larger than this is not physically realizable (for pressure)."
            )

        rho_host = np.asarray(rho_range)
        if np.any(np.abs(rho_host) > rho_shift_absmax):
            raise ValueError("Absolute value of shifts in rho must be less than 0.2.")

        if int(weights.size) != N_weights:
            raise ValueError(
                "weights array must be of length: len(k_range) * len(rho_range). "
                f"Got {weights.size} but expected {N_weights}."
            )

        if float(jnp.min(weights)) < 0:
            raise ValueError("weights must be nonnegative.")
        #------------------------------------------------

        # Attribute setup:
        self._p_axis = p_axis
        self._k_range = k_range
        self._rho_range = rho_range
        self._rho_grid = rho_grid   # <-- STATIC ATTRIBUTE (see _static_attrs)
        self._params = weights
        #---------------------
    #-------------------------------------------------


    #--------
    @property
    def params(self):
        """
        ndarray: Parameters for computation. Each weight is
        multiplied by a logistic function which is given a k
        from k_range and rho_shift from rho_range.
        """
        return self._params

    @params.setter
    def params(self, new):
        new = jnp.atleast_1d(jnp.asarray(new, dtype=self._params.dtype))
        N = int(self._k_range.size * self._rho_range.size)
        if int(new.size) != N:
            raise ValueError(
                "params must be of length: len(k_range) * len(rho_range). "
                f"Got {new.size} but expected {N}."
            )
        self._params = new
    #---------------------


    #-----------------------------------------------------
    def logistic_super(self, rho=None, params=None, dr=0):
        """
        Generates a family of logistic functions over k_range and rho_range,
        then creates the weighted superposition.
        """
        dtype = self._params.dtype

        #-----------
        # None cases
        if rho is None:
            rho = self._rho_grid
        else:
            rho = jnp.atleast_1d(jnp.asarray(rho, dtype=dtype))

        if params is None:
            weights = self._params
        else:
            weights = jnp.atleast_1d(jnp.asarray(params, dtype=dtype))

        rho = rho.astype(dtype)
        weights = weights.astype(dtype)

        rho_0 = rho[:, None, None] - jnp.asarray(0.5, dtype=dtype)
        u = rho_0 - self._rho_range[None, None, :]
        k = self._k_range[None, :, None]

        f = 1 - (1 / (1 + jnp.exp(-k * u)))  # vectorized family of logistic funcs

        # Derivative order choice:
        if dr == 0:
            fam = f
        elif dr == 1:
            fam = -k * f * (1 - f)
        elif dr == 2:
            fam = (k**2) * f * (1 - f) * (1 - 2 * f)
        else:
            raise NotImplementedError("Only dr=0,1,2 implemented for LogisticProfile.")

        fam_flat = fam.reshape(rho.size, -1)
        superpos = fam_flat @ weights

        #-------------------------------------------------------------------
        eps = jnp.asarray(1e-8, dtype=dtype)

        rho_end = jnp.asarray([0.0, 1.0], dtype=dtype)
        rho0_end = rho_end[:, None, None] - jnp.asarray(0.5, dtype=dtype)
        u_end = rho0_end - self._rho_range[None, None, :]
        k_end = self._k_range[None, :, None]

        f_end = 1 - (1 / (1 + jnp.exp(-k_end * u_end)))
        f_end_flat = f_end.reshape(2, -1)
        s_end = f_end_flat @ weights
        norm_factor = jnp.asarray(1.0, dtype=dtype) / ((s_end[0] - s_end[1]) + eps)

        if dr == 0:
            superpos = (superpos - s_end[1]) * norm_factor
        else:
            superpos = superpos * norm_factor
        #-------------------------------------------------------------------

        return superpos
    #------------------------------------------------------------------------------------------------------------------------------


    #------------------------------------------------------
    def compute(self, grid, params=None, dr=0, dt=0, dz=0):
        """Compute values of profile at specified nodes."""
        dtype = self._params.dtype

        if (dt != 0) or (dz != 0):
            return jnp.zeros(grid.num_nodes, dtype=dtype)

        rho = jnp.asarray(grid.nodes[:, 0], dtype=dtype)

        if dr == 0:
            p = self._p_axis * self.logistic_super(rho=rho, params=params, dr=0)
            return p
        elif dr == 1:
            dpdr = self._p_axis * self.logistic_super(rho=rho, params=params, dr=1)
            return dpdr
        elif dr == 2:
            d2pdr2 = self._p_axis * self.logistic_super(rho=rho, params=params, dr=2)
            return d2pdr2
        else:
            raise NotImplementedError("Only dr=0,1,2 implemented for LogisticProfile.")
    #----------------------------------------------------------------------------------




    #--------
    @property
    def params(self):
        """
        ndarray: Parameters for computation. Each weight is 
        multiplied by a logistic function which is given a k 
        from k_range and rho_shift from rho_range.
        """
        return self._params
    

    @params.setter
    def params(self, new):
        new = jnp.atleast_1d(jnp.asarray(new))
        N = int(self._k_range.size * self._rho_range.size)
        if int(new.size) != N:
            raise ValueError(
                "params must be of length: len(k_range) * len(rho_range). "
                f"Got {new.size} but expected {N}."
            )
        self._params = new
    #---------------------  
    




    #-----------------------------------------------------
    def logistic_super(self, rho=None, params=None, dr=0):
        """
        Generates a family of logistic functions over k_range and rho_range,
        then creates the weighted superposition.

        --------- Parameters -------------------------------------
        rho: array-like or None
            locations to evaluate the profile at. If None, uses self._rho_grid.
        params: array-like or None
            weights to use. If None, uses self._params.

        --------- Returns ----------------------------------------
        superpos: array-like
            1-D array that is a superposition of all logistic
            function permutations of k_range and rho_range,
            weighted by the optimization parameter "weights".
        """
        #-----------
        # None cases
        if rho is None:
            rho = self._rho_grid
        else:
            rho = jnp.atleast_1d(jnp.asarray(rho))

        if params is None:
            weights = self._params
        else:
            weights = jnp.atleast_1d(jnp.asarray(params))

        rho_0 = rho[:, None, None] - 0.5
        u = rho_0 - self._rho_range[None, None, :]
        k = self._k_range[None, :, None]

        f = 1 - (1 / (1 + jnp.exp(-k * u))) # vectorized family of logistic funcs

        # Derivative order choice:
        if dr == 0:
            fam = f
        elif dr == 1:
            fam = -k * f * (1 - f)
        elif dr == 2:
            fam = (k**2) * f * (1 - f) * (1 - 2 * f)
        else:
            raise NotImplementedError("Only dr=0,1,2 implemented for LogisticProfile.")

        # Collapsing k dimension and rho_shift dimension into one, such that fam_flat[i, j]
        # gives the value of the jth basis logistic function, evaluated at the ith grid point:
        fam_flat = fam.reshape(rho.size, -1) 
        # Multiplying each j logistic function by a weight and summing, giving shape
        # (# grid points,):
        superpos = fam_flat @ weights 
        #----------------------------


        # Normalization factor repeats the above process, but using only 
        # endpoint values such that 0th, 1st and 2nd derivatives always 
        # normalized, and 0th derivative = 1 at rho = 0 and = 0 and rho = 1:
        #-------------------------------------------------------------------
        eps = 1e-9  # small number to avoid divide-by-zero if s(0) ~ s(1)

        rho_end = jnp.array([0.0, 1.0])  # evaluate endpoints: axis rho = 0 and edge rho = 1
        rho0_end = rho_end[:, None, None] - 0.5  # reshape to (2,1,1) and shift so rho = 0.5 is logistic center
        u_end = rho0_end - self._rho_range[None, None, :]  # logistic argument u for each endpoint and each rho_shift (broadcasted)
        k_end = self._k_range[None, :, None]  # reshape k to broadcast over endpoints and shifts
        
        f_end = 1 - (1 / (1 + jnp.exp(-k_end * u_end)))  # dr = 0 logistic basis at endpoints; shape (2, N_k, N_shift)
        f_end_flat = f_end.reshape(2, -1)  # collapse (k, rho_shift) into basis index; shape (2, N_k * N_shift)
        s_end = f_end_flat @ weights  # raw superposition at endpoints: s_end[0] = s(0), s_end[1] = s(1)
        norm_factor = 1.0 / ((s_end[0] - s_end[1]) + eps)  # normalization multiplier based on axis-to-edge drop

        if dr == 0:
            superpos = (superpos - s_end[1]) * norm_factor  # shift so value at rho = 1 is 0, then scale so value at rho = 0 is ~1
        else:
            superpos = superpos * norm_factor  # derivatives: only scale since constant shifts vanish under d/dρ
        #-------------------------------------------------------------------------------------------------------

        return superpos
    #------------------------------------------------------------------------------------------------------------------------------


    #------------------------------------------------------
    def compute(self, grid, params=None, dr=0, dt=0, dz=0):
        """Compute values of profile at specified nodes.

        Parameters
        ----------
        grid : Grid
            Locations to compute values at.
        params : array-like
            Weights to use for the logistic superposition. If not given, uses self.params.
        dr, dt, dz : int
            derivative order in rho, theta, zeta

        Returns
        -------
        values : ndarray
            values of the profile or its derivative at the points specified

        """
        if (dt != 0) or (dz != 0):
            return jnp.zeros(grid.num_nodes)

        rho = grid.nodes[:, 0]

        if dr == 0:
            p = self._p_axis * self.logistic_super(rho=rho, params=params, dr=0)
            return p
        #
        elif dr == 1:
            dpdr = self._p_axis * self.logistic_super(rho=rho, params=params, dr=1)
            return dpdr
        #
        elif dr == 2:
            d2pdr2 = self._p_axis * self.logistic_super(rho=rho, params=params, dr=2)
            return d2pdr2
        #
        else:
            raise NotImplementedError("Only dr=0,1,2 implemented for LogisticProfile.")
    #----------------------------------------------------------------------------------
























    
   











