#NOTES:
# consider upper limit to k_max, as decided by theory


import os
import numpy as np
import matplotlib.pyplot as plt
from desc.profiles import _Profile
from desc.backend import jit, jnp, put, sign, jax





#--------------------------------- CLASS FOR OPTIMIZER ---------------------------------
class LogisticProfile(_Profile):
    """
    Profile is a superpostion of logistic/sigmoid functions, 
    normalized to the input on-axis (rho=0) maximum value. 
    Individual logistic functions are generated by combinations
    of given values for the steepness parameter k and shifts of
    the midpoint parameter rho_shift from rho = 0.5.
    
    -------- Parameters -----------------------
    weights: array-like
        1-D array with optimizable weights for each combo 
        of elements within k_range and rho_range.
    p_axis: scalar
        Maximum pressure on the axis, un-normalized.
    k_range: array-like
        1-D array of parameter k in the logistic function,
        corresponding to 'steepness'.
    rho_range: array-like
        1-D array of parameter rho-shift, horizontal offset
        of the logistic function from its center at rho = 0.5.
    name: str
        Optional name of the profile.
    --------- Returns ---------------
    
    """
    _io_attrs_ = _Profile._io_attrs_ + ["_params", "_p_axis", "_k_range", "_rho_range", "_rho_grid"]
    _static_attrs = _Profile._static_attrs + ["_k_range", "_rho_range"]

    #------------
    def __init__(
        self,
        weights=None,
        p_axis=None,
        k_range=None,
        rho_range=None,
        rho_grid=None,
        name="",
    ):
        super().__init__(name)

        seed = jax.random.PRNGKey(0)

        p_axis_default = 1e4
        k_range_default = jnp.linspace(10, 20, 5)
        rho_range_default = jnp.linspace(-0.2, 0.2, 4)

        k_max = 40
        rho_shift_absmax = 0.2

        if any(x is None for x in (p_axis, k_range, rho_range)):
            print(
                "Default LogisticProfile settings:\n"
                f"  p_axis   = {p_axis_default}\n"
                f"  k_range  = {k_range_default}\n"
                f"  rho_range= {rho_range_default}"
            )

        if p_axis is None:
            p_axis = p_axis_default
        if k_range is None:
            k_range = k_range_default
        if rho_range is None:
            rho_range = rho_range_default

        if rho_grid is None:
            raise ValueError("rho_grid must be provided.")

        k_range = jnp.atleast_1d(jnp.asarray(k_range))
        rho_range = jnp.atleast_1d(jnp.asarray(rho_range))
        rho_grid = jnp.atleast_1d(jnp.asarray(rho_grid))

        N = int(k_range.size * rho_range.size)
        weights_default = jax.random.uniform(seed, shape=(N,), minval=0.0, maxval=1.0 / N)

        if weights is None:
            weights = weights_default
        weights = jnp.atleast_1d(jnp.asarray(weights))

        if int(weights.size) != N:
            raise ValueError(
                "weights array must be of length: len(k_range) * len(rho_range). "
                f"Got {weights.size} but expected {N}."
            )

        if p_axis < 0:
            raise ValueError("Pressure must be positive.")

        for k in np.asarray(k_range):
            if k < 0:
                raise ValueError("k must be positive")
            if k > k_max:
                raise ValueError(
                    "Maximum k is 40. Larger than this is not physically realizable (for pressure)."
                )

        for rho_shift in np.asarray(rho_range):
            if np.abs(rho_shift) > rho_shift_absmax:
                raise ValueError("Absolute value of shifts in rho must be less than 0.2.")

        self._p_axis = float(p_axis)
        self._k_range = k_range
        self._rho_range = rho_range
        self._rho_grid = rho_grid

        self._params = weights
    #-------------------------




    #--------
    @property
    def params(self):
        """
        ndarray: Parameters for computation. Each weight is 
        multiplied by a logistic function which is given a k 
        from k_range and rho_shift from rho_range.
        """
        return self._params
    

    @params.setter
    def params(self, new):
        new = jnp.atleast_1d(jnp.asarray(new))
        N = int(self._k_range.size * self._rho_range.size)
        if int(new.size) != N:
            raise ValueError(
                "params must be of length: len(k_range) * len(rho_range). "
                f"Got {new.size} but expected {N}."
            )
        self._params = new
    #---------------------  
    





    #-----------------------------------------------
    def logistic_super(self, rho=None, params=None, dr=0):
        """
        Generates a family of logistic functions over k_range and rho_range,
        then creates the weighted superposition.

        --------- Parameters -------------------------------------
        rho: array-like or None
            locations to evaluate the profile at. If None, uses self._rho_grid.
        params: array-like or None
            weights to use. If None, uses self._params.

        --------- Returns ----------------------------------------
        superpos: array-like
            1-D array that is a superposition of all logistic
            function permutations of k_range and rho_range,
            weighted by the optimization parameter "weights".
        """
        if rho is None:
            rho = self._rho_grid
        else:
            rho = jnp.atleast_1d(jnp.asarray(rho))

        if params is None:
            weights = self._params
        else:
            weights = jnp.atleast_1d(jnp.asarray(params))

        rho_0 = rho[:, None, None] - 0.5
        u = rho_0 - self._rho_range[None, None, :]
        k = self._k_range[None, :, None]

        f = 1 - (1 / (1 + jnp.exp(-k * u)))

        if dr == 0:
            fam = f
        elif dr == 1:
            fam = -k * f * (1 - f)
        elif dr == 2:
            fam = (k**2) * f * (1 - f) * (1 - 2 * f)
        else:
            raise NotImplementedError("Only dr=0,1,2 implemented for LogisticProfile.")

        fam_flat = fam.reshape(rho.size, -1)
        superpos = fam_flat @ weights

        if dr == 0:
            superpos = superpos / (superpos[0] - superpos[-1] + 0.05)

        return superpos
    #------------------


    #------------------------------------------------------
    def compute(self, grid, params=None, dr=0, dt=0, dz=0):
        """Compute values of profile at specified nodes.

        Parameters
        ----------
        grid : Grid
            Locations to compute values at.
        params : array-like
            Weights to use for the logistic superposition. If not given, uses self.params.
        dr, dt, dz : int
            derivative order in rho, theta, zeta

        Returns
        -------
        values : ndarray
            values of the profile or its derivative at the points specified

        """
        if (dt != 0) or (dz != 0):
            return jnp.zeros(grid.num_nodes)

        rho = grid.nodes[:, 0]

        if dr == 0:
            p = self._p_axis * self.logistic_super(rho=rho, params=params, dr=0)
            return p

        elif dr == 1:
            dpdr = self._p_axis * self.logistic_super(rho=rho, params=params, dr=1)
            return dpdr

        elif dr == 2:
            d2pdr2 = self._p_axis * self.logistic_super(rho=rho, params=params, dr=2)
            return d2pdr2

        else:
            raise NotImplementedError("Only dr=0,1,2 implemented for LogisticProfile.")
    #----------------------------------------------------------------------------------
























    
   











